spring:
  application:
    name: hackathon
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
server:
  port: 80


# SQL statements and parameters
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        type: trace
        stat: debug